name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  IMAGE_NAME: ghcr.io/bitvavo/bootcamp-slack-app

jobs:
  test:
    runs-on: ubuntu-latest-4core

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.4
        with:
          deno-version: "~1.42"

      - name: Run formatter
        run: deno fmt --check

      - name: Run tests
        run: deno test -A

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - uses: bitvavo/pipelines/actions/container-build@container-build/v1
        with:
          image: "${{ env.IMAGE_NAME }}"
          context: "."
          push: false
          file: "Dockerfile"
          tags: "${{ github.sha }}"
          ghcr-username: ${{ github.actor }}
          ghcr-token: ${{ secrets.GITHUB_TOKEN }}
          wiz-client-id: ${{ secrets.WIZ_CLIENT_ID }}
          wiz-client-secret: ${{ secrets.WIZ_CLIENT_SECRET }}
