name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Next Version'
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.release_token }}

      - name: Set author in Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Change version
        run: |
          mv deno.json deno.json.bak
          jq '.version = "${{ github.event.inputs.version }}"' deno.json.bak > deno.json

      - name: Commit version change
        run: |
          git add deno.json
          git commit -m "${{ github.event.inputs.version }}"
          git tag "v${{ github.event.inputs.version }}"
          git push --tags origin ${{ github.ref_name }}

      - uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.event.inputs.version }}
          draft: true
