name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Next Version'
        required: true

env:
  IMAGE_NAME: ghcr.io/bitvavo/bootcamp-slack-app

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set author in Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Change version
        run: |
          mv deno.json deno.json.bak
          jq '.version = "${{ github.event.inputs.version }}"' deno.json.bak > deno.json

      - name: Commit version change
        run: |
          git add deno.json
          git commit -m "${{ github.event.inputs.version }}"
          git tag "v${{ github.event.inputs.version }}"

      - uses: bitvavo/pipelines/actions/container-build@container-build/v1
        with:
          image: "${{ env.IMAGE_NAME }}"
          context: "."
          push: true
          file: "Dockerfile"
          tags: "v${{ github.event.inputs.version }}"
          ghcr-username: ${{ github.actor }}
          ghcr-token: ${{ secrets.GITHUB_TOKEN }}
          wiz-client-id: ${{ secrets.WIZ_CLIENT_ID }}
          wiz-client-secret: ${{ secrets.WIZ_CLIENT_SECRET }}

      - name: Push release commit
        run: |
          git push --tags origin ${{ github.ref_name }}

      - uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.event.inputs.version }}
          draft: true
